#!/usr/bin/env python3
"""Stage 3b: extract the full, unfiltered EventID inventory for every EVTX sample group.

evtx is a binary format. 04_diagnose_misses.py used to extract EventIDs by
regex-searching the group's staged files as text, which works for
attack_data's XML/.log files but reads nothing at all from a binary .evtx
file, silently returning an empty set. That bug is documented in FINDINGS.md
under "Bug found during this project: the EVTX EventID extraction defect".

This script fixes it by asking Zircolite (already vendored and used by this
project, never Zircolite's binary decoding is trusted, no separate evtx
parsing library is introduced) to decode each EVTX group's events to JSON
itself, with:

  --no-event-filter   disables Zircolite's own early channel/EventID
                       pre-filter, which otherwise silently drops events
                       whose (channel, EventID) pair is not targeted by ANY
                       loaded rule, before rule matching even runs. Without
                       this flag, the flattened dump would UNDERCOUNT
                       EventIDs for the same reason the old text-regex bug
                       undercounted them: silently dropping ones no rule
                       happened to be looking for.
  --keepflat          writes every parsed event (not just rule matches) as
                       flattened JSONL to flattened_events_<rand>.json in the
                       current working directory.
  -n                  suppresses the normal detections output file (this
                       script does not care about rule matches here; that is
                       03_build_matrix.py's job, unchanged).

This is read-only against evidence/samples/ (already staged, gitignored,
regenerated by 01_prepare_samples.py) and never touches evidence/03_matrix.json
or evidence/zircolite_raw/, i.e. the scored matrix is untouched by this fix.

Output: evidence/03b_evtx_eventid_inventory.json, mapping
"<technique>/<group>" -> sorted list of EventID strings found in that group's
raw EVTX files, or null if extraction failed for that group (e.g. Zircolite
errored, or the group has zero .evtx files to inventory in the first place).
A null here is what lets 04_diagnose_misses.py report UNDETERMINED instead of
silently assuming zero EventIDs present.
"""
from __future__ import annotations

import json
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SAMPLES_DIR = ROOT / "evidence" / "samples"
OUT_PATH = ROOT / "evidence" / "03b_evtx_eventid_inventory.json"

VENV_PY = Path("/home/kali/director/projects/detection-as-code/.venv/bin/python3")
ZIRCOLITE_PY = Path("/home/kali/director/projects/detection-as-code/vendor/Zircolite/zircolite.py")
RULESET = Path("/home/kali/director/projects/detection-as-code/vendor/Zircolite/rules/rules_windows_merged.json")

TIMEOUT_S = 300


def extract_eventids(evtx_dir: Path, log_lines: list[str]) -> list[str] | None:
    """Run Zircolite against evtx_dir with no event filter, keeping every
    flattened event, and return the sorted set of EventID values found.

    Returns None if the run failed or produced no flattened output, so the
    caller can distinguish "genuinely ran and found nothing" (empty list)
    from "could not determine" (None).
    """
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        cmd = [
            str(VENV_PY), str(ZIRCOLITE_PY),
            "-e", str(evtx_dir),
            "--no-event-filter",
            "--keepflat",
            "-r", str(RULESET),
            "-n", "-q",
        ]
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=TIMEOUT_S, cwd=tmp_path)
        log_lines.append(f"cmd: {' '.join(cmd)} (cwd={tmp_path})")
        log_lines.append(f"returncode: {proc.returncode}")
        if proc.returncode != 0:
            log_lines.append(f"--- stderr ---\n{proc.stderr}")
            return None

        flat_files = list(tmp_path.glob("flattened_events_*.json"))
        if not flat_files:
            log_lines.append("no flattened_events_*.json produced")
            return None

        ids: set[str] = set()
        event_count = 0
        for flat_file in flat_files:
            for line in flat_file.read_text(errors="replace").splitlines():
                line = line.strip()
                if not line:
                    continue
                try:
                    event = json.loads(line)
                except json.JSONDecodeError:
                    continue
                event_count += 1
                eid = event.get("EventID")
                if eid is not None:
                    ids.add(str(eid))
        log_lines.append(f"flattened events read: {event_count}, distinct EventIDs: {len(ids)}")
        return sorted(ids, key=lambda x: int(x) if x.lstrip("-").isdigit() else 0)


def main() -> None:
    inventory: dict[str, list[str] | None] = {}
    all_log_lines: list[str] = []

    for technique_dir in sorted(SAMPLES_DIR.iterdir()):
        if not technique_dir.is_dir():
            continue
        for group_dir in sorted(technique_dir.iterdir()):
            if not group_dir.is_dir():
                continue
            evtx_files = list(group_dir.glob("*.evtx"))
            if not evtx_files:
                continue  # not an EVTX group; 04_diagnose_misses.py's own XML regex handles these fine
            key = f"{technique_dir.name}/{group_dir.name}"
            print(f"[{key}] extracting full EventID inventory from {len(evtx_files)} .evtx file(s) via Zircolite ...")
            log_lines: list[str] = []
            ids = extract_eventids(group_dir, log_lines)
            all_log_lines.append(f"=== {key} ===")
            all_log_lines.extend(log_lines)
            all_log_lines.append("")
            inventory[key] = ids
            print(f"  -> {ids if ids is not None else 'FAILED, will report UNDETERMINED'}")

    OUT_PATH.write_text(json.dumps(inventory, indent=2) + "\n")
    log_path = ROOT / "evidence" / "03b_evtx_eventid_inventory.log.txt"
    log_path.write_text("\n".join(all_log_lines) + "\n")
    print(f"\nwrote {OUT_PATH}")
    print(f"wrote {log_path}")


if __name__ == "__main__":
    main()
