logger:
  file:
    path: /opt/open5gs/var/log/open5gs/sgwu.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
# max:
#   ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

sgwu:
  pfcp:
    server:
    - dev: eth0
  gtpu:
    server:
    - dev: eth0
