[install]
is_configured = 1

[ui]
is_visible = 0
label = Splunk Ingest Pipeline (UF)

[launcher]
author = Splunk Ingestion Portfolio
description = UF-side outputs.conf/inputs.conf for the splunk-ingest-pipeline project.
version = 1.0.0
